# Generated by Django 5.0.4 on 2024-04-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='creator',
        ),
    ]
