# Generated by Django 5.0.4 on 2024-04-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_organization_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='creator_id',
            field=models.BigIntegerField(default=0, verbose_name='create'),
            preserve_default=False,
        ),
    ]
